#!/usr/bin/env bash
# uploads a file to a server

error_msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ "$4" ]; then
    path_to_file="$1"
    ip="$2"
    username="$3"
    path_to_ssh_key="$4"
   scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip:~"
elif [ "$3" ]; then
     scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "$error_msg";
fi
