#!/usr/bin/env bash
#install nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo 'Hello World!' >  /var/www/html/index.html 

#testing  configuration
#sudo nginx -t
#sudo service nginx reload
sudo service nginx start
