#!/usr/bin/env bash
#install load balancer

sudo apt-get -y update
apt-get -y install haproxy


# edit config file
server_config=\
"
frontend haproxy_in
        bind *:80
        mode http
        default_backend haproxy_http
backend haproxy_http
        balance roundrobin
        server 496943-web-01 54.236.56.171:80 check
        server 496943-web-02 52.90.14.249:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
