#!/usr/bin/env bash
# install the ufw firewall and block all incoming traffic

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
echo "y" | sudo ufw enable
